<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>XAOCEN.ReWiFi</AssemblyName>
    <Product>XAOCEN ReWiFi</Product>
    <AssemblyTitle>XAOCEN ReWiFi</AssemblyTitle>
    <Title>XAOCEN ReWiFi</Title>
    <Company>XAOCEN STUDIO</Company>
    <RootNamespace>XAOCEN.ReWiFi</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>1.5</Version>
    <InformationalVersion>1.5</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AssemblyVersion>1.5.0.0</AssemblyVersion>
    <FileVersion>1.5.0.0</FileVersion>
    <ApplicationIcon>Assets\xaocen-rewifi_rounded.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\xaocen-rewifi_rounded.png" />
    <EmbeddedResource Include="Assets\About.html" />
    <EmbeddedResource Include="Assets\xaocen-rewifi.png" />
  </ItemGroup>
</Project>
